MFH:
* Merge all the latest buildscript code from pointyhat.  This will detect
  more leftovers at each stage of the build, plus detect when a port tries
  to change something outside of WRKDIR before the installation phase.

* Fix leftover detection once and for all.

This commit brings with it a micro schema change.

diff --git a/buildscript b/buildscript
--- a/buildscript
+++ b/buildscript
@@ -7,7 +7,7 @@ mountprocfs() {
     arch=$1
 
     if [ ${arch} = "i386" -o ${arch} = "amd64" ]; then
-        # JDK ports need linprocfs :(
+	# JDK ports need linprocfs :(
 	mkdir -p /compat/linux/proc
 	mount_linprocfs linprocfs /compat/linux/proc
     fi
@@ -30,10 +30,13 @@ cleanup() {
     tar cfjC /tmp/work.tbz ${objdir}/.. work
   fi
 
-  cat /tmp/make.log${status}
+  if [ ${status} -gt 0 ]; then
+      cat /tmp/make.log${status}
+  fi
+
   echo 1 > /tmp/status
   echo "================================================================"
-  echo -n "build ended at "
+  echo -n "build of ${dir} ended at "
   date
 
   exit 0
@@ -73,22 +76,39 @@ del_pkg() {
   cd /tmp/depends
   export PKG_PATH=/tmp/depends
   if [ ! -z "${pkgs}" ]; then
-    unset delpkg
-    for i in $pkgs; do
-      base=$(basename $i .tgz)
-      base=$(basename $base .tbz)
-      if ! pkg_info -q -e $base; then
-        echo "skipping $base, already deleted"
+    recursion=1
+    dellist=""
+    while [ $recursion -eq 1 ]; do
+      unset delpkg nextpkg
+      recursion=0
+      for i in $pkgs; do
+        base=$(basename $i .tgz)
+        base=$(basename $base .tbz)
+        if [ -s /var/db/pkg/${base}/+REQUIRED_BY ]; then
+          recursion=1
+          nextpkg="${base} ${nextpkg}"
+        elif [ -d /var/db/pkg/${base}/ ]; then
+          delpkg="${base} ${delpkg}"
+        fi
+      done
+      pkgs="${nextpkg}"
+      if [ "$dellist" != "" -a "$dellist" = "$delpkg" ]; then
+        echo "deleted list =\""$dellist"\", packages to delete ="\"$delpkg\"
+        echo "The following packages were left behind (perhaps your dependency list is incomplete):"
+        ls /var/db/pkg
+        echo "error in pkg_delete, exiting"
+        cleanup 0
       else
-	delpkg="${base} ${delpkg}"
+        for j in ${delpkg}; do
+          echo "Deleting ${j}"
+          if ! (pkg_delete -f $j); then
+            echo "--> error in pkg_delete, exiting"
+            cleanup 0
+          fi
+        done
+        dellist=$delpkg
       fi
     done
-    echo "Deleting $delpkg"
-    if ! (echo ${delpkg} | xargs pkg_delete -rf); then
-      echo "error in pkg_delete, exiting"
-      echo "1" > /tmp/status
-      exit 1
-    fi
   fi
 }
 
@@ -114,10 +134,26 @@ if [ $phase = 1 ]; then
   echo "BUILD_DEPENDS=${BD}"
   echo "RUN_DEPENDS=${RD}"
 
-  add_pkg $FD
-
   #Allow ports to notice they're being run in Tinderbox
   export PACKAGE_BUILDING=1
+
+  # Files we do not care about changing between pre-build and post-cleanup
+  cat > /tmp/mtree.preexclude <<EOF
+./root/*
+./var/*
+./tmp/*
+./etc/make.conf.bak
+./etc/make.conf
+./work/*
+./compat/linux/proc
+./usr/share/man/cat*/*
+./usr/local/etc/apache/httpd.conf
+./usr/local/etc/apache2/httpd.conf
+EOF
+  # Record a "pristine" mtree.
+  mtree -X /tmp/mtree.preexclude -xcn -k uid,gid,mode -p / > /tmp/mtree.pristine
+
+  add_pkg $FD
 
   cd $dir || exit 1
   pkgname=$(make package-name)
@@ -131,6 +167,8 @@ if [ $phase = 1 ]; then
     cleanup 1
   fi
 
+  del_pkg $FD
+
 else
 
   cd $dir || exit 1
@@ -138,11 +176,17 @@ else
 
   echo "================================================================"
   echo "====================<phase 2: make extract>===================="
+
   add_pkg ${ED}
   cd $dir
   /pnohang $TIMEOUT /tmp/make.log2 ${pkgname} make extract || cleanup 2
   cat /tmp/make.log2
   del_pkg ${ED}
+
+  # Fetch depends still need to be here for 'make extract' since that target
+  # always reruns 'make fetch' due to the lack of fetch cookie (and no place
+  # to put it since WRKDIR isn't created by 'make fetch')
+  del_pkg $FD
 
   echo "================================================================"
   echo "====================<phase 3: make patch>===================="
@@ -154,7 +198,24 @@ else
 
   echo "================================================================"
   echo "====================<phase 4: make build>===================="
+
   add_pkg ${BD}
+
+  # Files we do not care about changing between pre-build and post-cleanup
+  cat > /tmp/mtree.buildexclude <<EOF
+./var/log/*
+./tmp/*
+./work/*
+./compat/linux/proc
+./root/*
+./var/mail/*
+./var/tmp/*
+./usr/share/man/cat*/*
+./usr/local/etc/apache/httpd.conf
+./usr/local/etc/apache2/httpd.conf
+EOF
+  # Record a "pristine" mtree.
+  mtree -X /tmp/mtree.buildexclude -xcn -k uid,gid,mode -p / > /tmp/mtree.prebuild
 
   xvfb=0
   if which -s Xvfb; then
@@ -183,8 +244,26 @@ else
   cat /tmp/make.log4
 
   echo "================================================================"
-  echo "====================<phase 5: make package>===================="
+  echo "====================<phase 5: make test>===================="
+  cd $dir
+  /pnohang $TIMEOUT /tmp/make.log5 ${pkgname} make -k regression-test
+  cat /tmp/make.log5
+
+  mtree -X /tmp/mtree.buildexclude -x -f /tmp/mtree.prebuild -p / | egrep -v "^(usr/local/var|usr/X11R6/lib/X11/xserver/SecurityPolicy|usr/local/share/nls/POSIX|usr/local/share/nls/en_US.US-ASCII|etc/services|compat |usr/X11R6 |etc/manpath.config|etc/.*.bak|usr/local/info/dir|usr/X11R6/lib/X11/fonts/.*/fonts\.|usr/(X11R6|local)/man/..( |/man. )|usr/X11R6/lib/X11/fonts/TrueType )" > /tmp/list.preinstall
+
+  if [ -s /tmp/list.preinstall ]; then
+      echo "================================================================"
+      echo "Fatal error: filesystem was touched prior to 'make install' phase"
+      cat /tmp/list.preinstall
+      echo "================================================================"
+      cleanup 0
+  fi
+
+  echo "================================================================"
+  echo "====================<phase 6: make install>===================="
+
   add_pkg ${RD}
+
   cat > /tmp/mtree.exclude <<EOF
 ./root/*
 ./var/*
@@ -195,61 +274,118 @@ else
 ./compat/linux/proc
 EOF
   mtree -X /tmp/mtree.exclude -xcn -k uid,gid,mode -p / > /tmp/mtree
+
   cd $dir
-  if /pnohang $TIMEOUT /tmp/make.log5 ${pkgname} make package; then
-    cat /tmp/make.log5
+  if /pnohang $TIMEOUT /tmp/make.log6 ${pkgname} make install; then
+    cat /tmp/make.log6
     echo "0" > /tmp/status
-    prefix=$(make -V PREFIX)
-    del_pkg ${pkgname}
+  else
+    cleanup 6
+  fi
 
-    mtree -X /tmp/mtree.exclude -x -f /tmp/mtree -p / | egrep -v "^(usr/local/var|usr/X11R6/lib/X11/xserver/SecurityPolicy|usr/local/share/nls/POSIX|usr/local/share/nls/en_US.US-ASCII|etc/services|compat |usr/X11R6 |etc/manpath.config|etc/.*.bak|usr/local/info/dir|usr/X11R6/lib/X11/fonts/.*/fonts\.|usr/(X11R6|local)/man/..( |/man. )|usr/X11R6/lib/X11/fonts/TrueType )" > /tmp/list3
+  echo "================================================================"
+  echo "====================<phase 7: make package>===================="
+  cd $dir
+  if /pnohang $TIMEOUT /tmp/make.log7 ${pkgname} make package; then
+      cat /tmp/make.log7
+      echo "0" > /tmp/status
+      prefix=$(make -V PREFIX)
+      del_pkg ${pkgname}
+  else
+      cleanup 7
+  fi
 
-    if [ -s /tmp/list3 ]; then
+  mtree -X /tmp/mtree.exclude -x -f /tmp/mtree -p / | egrep -v "^(usr/local/var|usr/X11R6/lib/X11/xserver/SecurityPolicy|usr/local/share/nls/POSIX|usr/local/share/nls/en_US.US-ASCII|etc/services|compat |usr/X11R6 |etc/manpath.config|etc/.*.bak|usr/local/info/dir|usr/X11R6/lib/X11/fonts/.*/fonts\.|usr/(X11R6|local)/man/..( |/man. )|usr/X11R6/lib/X11/fonts/TrueType )" > /tmp/list3
+
+  dirty=0
+  if [ -s /tmp/list3 ]; then
+    cd /
+    grep ' extra$' /tmp/list3 | awk '{print $1}' | xargs -J % find % -ls > /tmp/list4
+    grep ' missing$' /tmp/list3 > /tmp/list5
+    grep -vE ' (extra|missing)$' /tmp/list3 > /tmp/list6
+    if [ "x${PLISTCHECK}" != "x" ]; then
+      if grep -vqE "(usr/X11R6|usr/local)/etc/" /tmp/list4; then
+        echo "1" > /tmp/status
+        dirty=1
+      fi
+      if [ -s /tmp/list5 -o -s /tmp/list6 ]; then
+        echo "1" > /tmp/status
+        dirty=1
+      fi
+    fi
+      echo "================================================================"
+  fi
+
+
+  echo
+  echo "=== Checking filesystem state"
+
+  if [ -s /tmp/list4 ]; then
+    echo "list of extra files and directories in / (not present before this port was installed but present after it was deinstalled)"
+    cat /tmp/list4
+    touch /tmp/leftovers
+  fi
+  if [ -s /tmp/list5 ]; then
+    echo "list of files present before this port was installed but missing after it was deinstalled)"
+    cat /tmp/list5
+    touch /tmp/leftovers
+  fi
+  if [ -s /tmp/list6 ]; then
+    echo "list of filesystem changes from before and after port installation and deinstallation"
+    cat /tmp/list6
+    touch /tmp/leftovers
+  fi
+  if [ "${dirty}" = 1 ]; then
+    cleanup 0
+  fi
+
+  # BUILD_DEPENDS need to be present at install-time, e.g. gmake
+  # Concatenate and remove duplicates
+  BRD=$(echo $BD $RD | tr ' ' '\n' | sort -u | tr '\n' ' ')
+  del_pkg ${BRD}
+  cd /var/db/pkg
+  if [ $(echo $(echo * | wc -c)) != 2 ]; then
+    echo "leftover packages:" *
+    del_pkg *
+    echo "1" > /tmp/status
+    cleanup 0
+  fi
+
+  # Compare the state of the filesystem now to clean system (should again be clean)
+  mtree -X /tmp/mtree.preexclude -x -f /tmp/mtree.pristine -p / | egrep -v "^(usr/local/var|usr/X11R6/lib/X11/xserver/SecurityPolicy|usr/local/share/nls/POSIX|usr/local/share/nls/en_US.US-ASCII|etc/services|compat |usr/X11R6 |etc/manpath.config|etc/.*.bak|usr/local/info/dir|usr/X11R6/lib/X11/fonts/.*/fonts\.|usr/(X11R6|local)/man/..( |/man. )|usr/X11R6/lib/X11/fonts/TrueType )" > /tmp/list3
+  echo
+  echo "=== Checking filesystem state after all packages deleted"
+
+  if [ -s /tmp/list3 ]; then
       cd /
       grep ' extra$' /tmp/list3 | awk '{print $1}' | xargs -J % find % -ls > /tmp/list4
       grep ' missing$' /tmp/list3 > /tmp/list5
       grep -vE ' (extra|missing)$' /tmp/list3 > /tmp/list6
       if [ "x${PLISTCHECK}" != "x" ]; then
-	if grep -vqE "(usr/X11R6|usr/local)/etc/" /tmp/list4; then
-          echo "1" > /tmp/status
-	fi
-	if [ -s /tmp/list5 ]; then
-	  echo "1" > /tmp/status
-	fi
+	  if grep -vqE "(usr/X11R6|usr/local)/etc/" /tmp/list4; then
+	      #echo "1" > /tmp/status
+	  fi
+	  if [ -s /tmp/list5 ]; then
+	      #echo "1" > /tmp/status
+	  fi
       fi
       echo "================================================================"
-    fi
 
-    # BUILD_DEPENDS need to be present at install-time, e.g. gmake
-    # Concatenate and remove duplicates
-    BRD=$(echo $BD $RD | tr ' ' '\n' | sort -u | tr '\n' ' ')
-    del_pkg ${BRD}
-    cd /var/db/pkg
-    if [ $(echo $(echo * | wc -c)) != 2 ]; then
-      echo "leftover packages:" *
-      del_pkg *
-    fi
-
-    echo
-    echo "=== Checking filesystem state"
-
-    if [ -s /tmp/list4 ]; then
-      echo "list of extra files and directories in / (not present before this port was installed but present after it was deinstalled)"
-      cat /tmp/list4
-    fi
-    if [ -s /tmp/list5 ]; then
-      echo "list of files present before this port was installed but missing after it was deinstalled)"
-      cat /tmp/list5
-    fi
-    if [ -s /tmp/list6 ]; then
-      echo "list of filesystem changes from before and after port installation and deinstallation"
-      cat /tmp/list6
-      if [ "x${PLISTCHECK}" != "x" ]; then
-        echo "1" > /tmp/status
+      if [ -s /tmp/list4 ]; then
+	  echo "list of extra files and directories in / (not present on clean system but present after everything was deinstalled)"
+	  cat /tmp/list4
+	  touch /tmp/leftovers
       fi
-    fi
-  else
-    cleanup 5
+      if [ -s /tmp/list5 ]; then
+	  echo "list of files present on clean system but missing after everything was deinstalled)"
+	  cat /tmp/list5
+	  touch /tmp/leftovers
+      fi
+      if [ -s /tmp/list6 ]; then
+	  echo "list of filesystem changes from before and after all port installation/deinstallation"
+	  cat /tmp/list6
+	  touch /tmp/leftovers
+      fi
   fi
 
   if [ ${xvfb} = 1 ]; then
@@ -263,7 +399,7 @@ EOF
   fi
 
   echo "================================================================"
-  echo -n "build ended at "
+  echo -n "build of ${dir} ended at "
   date
 
 fi
