MFH:
Add a lot of new functionality to Tinderbox:

* Hooks : commands that can be run when certain operations are executed
          within Tinderbox
* Options Support : prompt user for port OPTIONS when adding ports to the
                    datastore
* Upward dependency tracking : Report which ports are affected when a port
                               build fails
* Duration and ETA tracking : Track a port's build duration and how long until
                              it will complete [1]

Bump version to 2.4.0.r1.

Submitted by:	edwin (based on) [1]

diff --git a/create b/create
--- a/create
+++ b/create
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright (c) 2005 FreeBSD GNOME Team <freebsd-gnome@FreeBSD.org>
+# Copyright (c) 2005-2007 FreeBSD GNOME Team <freebsd-gnome@FreeBSD.org>
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -24,7 +24,7 @@
 # OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 # SUCH DAMAGE.
 #
-# $MCom: portstools/tinderbox/create,v 1.5.2.5 2006/10/24 06:19:48 marcus Exp $
+# $MCom: portstools/tinderbox/create,v 1.5.2.6 2007/06/10 03:38:04 marcus Exp $
 #
 
 export defaultCvsupHost="cvsup12.FreeBSD.org"
@@ -326,9 +326,17 @@ createPortsTree () {
 
     # update ports tree if requested
     if [ "${updateProg}" != "NONE" ]; then
-	echo "${portsTreeName}: updating portstree with ${updateProg}..."
-	eval ${updateProg} >/dev/null 2>&1
+	execute_hook ${pb} "prePortsTreeUpdate" "PORTSTREE=${portsTreeName} UPDATE_CMD=${updateProg} PB=${pb}"
 	if [ $? != 0 ]; then
+	    echo "${portsTreeName}: terminating ports tree update since hook prePortsTreeUpdate failed."
+	    exit 1
+	fi
+	echo -n "${portsTreeName}: updating portstree with ${updateProg}..."
+	eval ${updateProg} >/dev/null 2>&1
+	rc=$?
+	execute_hook ${pb} "postPortsTreeUpdate" "PORTSTREE=${portsTreeName} UPDATE_CMD=${updateProg} PB=${pb} RC=${rc}"
+
+	if [ ${rc} != 0 ]; then
 	    echo "FAILED."
 	    exit 1
 	fi
diff --git a/mkbuild b/mkbuild
--- a/mkbuild
+++ b/mkbuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 #-
-# Copyright (c) 2004-2005 FreeBSD GNOME Team <freebsd-gnome@FreeBSD.org>
+# Copyright (c) 2004-2007 FreeBSD GNOME Team <freebsd-gnome@FreeBSD.org>
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -24,7 +24,7 @@
 # OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 # SUCH DAMAGE.
 #
-# $MCom: portstools/tinderbox/mkbuild,v 1.11.2.1 2005/11/25 02:13:36 marcus Exp $
+# $MCom: portstools/tinderbox/mkbuild,v 1.11.2.2 2007/06/10 03:38:04 marcus Exp $
 #
 
 
@@ -71,12 +71,20 @@ fi
 
 D=${pb}/${build}
 
+execute_hook ${pb} "preBuildExtract" "BUILD=${build} DESTDIR=${D} JAIL=${jail} PB=${pb}"
+if [ $? != 0 ]; then
+    echo "ERROR: Terminating Build extraction since hook preBuildExtract failed."
+    exit 1
+fi
+
 cleanup_mounts -d build -b ${build}
 chflags -R noschg ${D}
 rm -rf ${D}
 mkdir -p ${D}
 
 tar -C ${D} -xf ${pb}/jails/${jail}/${jail}.tar
+
+execute_hook ${pb} "postBuildExtract" "BUILD=${build} DESTDIR=${D} JAIL=${jail} PB=${pb} RC=0"
 
 # Finalize environment
 cp -f /etc/resolv.conf ${D}/etc
diff --git a/mkjail b/mkjail
--- a/mkjail
+++ b/mkjail
@@ -24,7 +24,7 @@
 # OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 # SUCH DAMAGE.
 #
-# $MCom: portstools/tinderbox/mkjail,v 1.27.2.3 2007/02/18 18:13:50 marcus Exp $
+# $MCom: portstools/tinderbox/mkjail,v 1.27.2.4 2007/06/10 03:38:04 marcus Exp $
 #
 
 
@@ -66,10 +66,19 @@ request_mount -q -r -d jail -j ${jail}
 
 update_cmd=$(${pb}/scripts/tc getSrcUpdateCmd -j ${jail})
 if [ ! -z "${update_cmd}" ]; then
+    execute_hook ${pb} "preJailUpdate" "JAIL=${jail} UPDATE_CMD=${update_cmd} PB=${pb}"
+    if [ $? != 0 ]; then
+        echo "ERROR: Terminating Jail update since hook preJailUpdate failed."
+        exit 1
+    fi
+
     echo "INFO: Updating jail with command ${update_cmd}"
     eval ${update_cmd} > ${pb}/jails/${jail}/update.log 2>&1
+    rc=$?
 
-    if [ $? != 0 ]; then
+    execute_hook ${pb} "postJailUpdate" "JAIL=${jail} RC=${rc} UPDATE_CMD=${update_cmd} PB=${pb}"
+
+    if [ ${rc} != 0 ]; then
 	echo "ERROR: Jail update failed."
 	exit 1
     fi
@@ -95,11 +104,20 @@ if [ -n "${JAIL_OBJDIR}" ]; then
     export MAKEOBJDIRPREFIX=${JAIL_OBJDIR}
 fi
 
+execute_hook ${pb} "preJailBuild" "JAIL=${jail} DESTDIR=${D} JAIL_OBJDIR=${JAIL_OBJDIR} SRCBASE=${SRCBASE} PB=${pb}"
+if [ $? != 0 ]; then
+    echo "ERROR: Terminating Jail build since hook preJailBuild failed."
+    exit 1
+fi
+
 cd ${SRCBASE}
 mkdir -p ${D}
 env DESTDIR=${D} make world
+rc=$?
 
-if [ $? != 0 ]; then
+execute_hook ${pb} "postJailBuild" "JAIL=${jail} DESTDIR=${D} JAIL_OBJDIR=${JAIL_OBJDIR} SRCBASE=${SRCBASE} PB=${pb} RC=${rc}"
+
+if [ ${rc} != 0 ]; then
     echo "ERROR: make world failed.  See above output."
     exit 1
 fi
diff --git a/portbuild b/portbuild
--- a/portbuild
+++ b/portbuild
@@ -42,19 +42,28 @@ cleanup()
     exit $error
 }
 
-clean_env()
+mark_failed()
 {
-    SAFE_VARS="PATH EDITOR BLOCKSIZE PAGER ENV"
-    old_IFS=${IFS}
-    IFS='
-'
-    for i in $(env); do
-	var=${i%%=*}
-	if ! echo ${SAFE_VARS} | grep -qw ${var}; then
-	    unset ${var}
-	fi
+    pb=$1
+    branch=$2
+    pkgname=$3
+    portdir=$4
+
+    mf="${pb}/builds/${branch}/Makefile"
+    if [ ! -f "${mf}" ]; then
+	return
+    fi
+
+    dependents=$(grep ${pkgname} ${mf} | grep '^[[:space:]]\{1,\}@' | awk '{print $NF}' | sed -e 's|^/usr/ports/||' | grep -v ${portdir})
+    if [ $? != 0 ]; then
+	return
+    fi
+
+    for dep in ${dependents}; do
+	${pb}/scripts/tc updatePortLastStatus -d ${dep} -b ${branch} -s DEPEND
+	${pb}/scripts/tc updatePortLastFailedDep -d ${dep} -b ${branch} -p ${portdir}
+        ${pb}/scripts/tc updatePortLastBuilt -d ${dep} -b ${branch}
     done
-    IFS=${old_IFS}
 }
 
 # Configurable variables
@@ -64,10 +73,10 @@ pb=$(type "$pb" | sed 's/^.* //g')
 pb=$(realpath $(dirname $pb))
 pb=${pb%%/scripts}
 
+. ${pb}/scripts/lib/tinderbox_shlib.sh
+
 # Clear out the environment.
 clean_env
-
-. ${pb}/scripts/lib/tinderbox_shlib.sh
 
 error=0
 init=0
@@ -147,12 +156,26 @@ echo ${pkgname}
 echo ${dirname}
 
 portdir=$(echo ${dirname} | sed -e 's|^/usr/ports/||')
+
+execute_hook ${pb} "prePortBuild" "PACKAGE_NAME=${pkgname} BUILD=${branch} JAIL=${jail} PORTSTREE=${portstree} CHROOT=${chroot} PORTDIR=${portdir} PB=${pb}"
+if [ $? != 0 ]; then
+    echo "Terminating build for ${pkgname} since prePortBuild hook failed"
+    ${pb}/scripts/tc updatePortLastBuilt -d ${portdir} -b ${branch}
+    ${pb}/scripts/tc updatePortLastStatus -d ${portdir} -b ${branch} -s FAIL
+    ${pb}/scripts/tc updatePortLastBuiltVersion -d ${portdir} -b ${branch} -v ${pkgname}
+    ${pb}/scripts/tc updatePortLastFailReason -d ${portdir} -b ${branch} -r "hook"
+    mark_failed ${pb} ${branch} ${pkgname} ${portdir}
+    exit 1
+fi
+
 if [ -f ${pb}/builds/${branch}/duds ]; then
     if grep -qxF ${pkgname} ${pb}/builds/${branch}/duds; then
         echo "skipping ${pkgname} (found in duds)"
 	${pb}/scripts/tc updatePortLastBuilt -d ${portdir} -b ${branch}
 	${pb}/scripts/tc updatePortLastStatus -d ${portdir} -b ${branch} -s DUD
 	${pb}/scripts/tc updatePortLastBuiltVersion -d ${portdir} -b ${branch} -v ${pkgname}
+	mark_failed ${pb} ${branch} ${pkgname} ${portdir}
+	execute_hook ${pb} "postPortBuild" "PACKAGE_NAME=${pkgname} BUILD=${branch} JAIL=${jail} PORTSTREE=${portstree} CHROOT=${chroot} STATUS=DUD PORTDIR=${portdir} PB=${pb}"
         exit 1
     fi
 fi
@@ -230,7 +253,8 @@ fi
 
 echo "building $pkgname in $chroot"
 
-${pb}/scripts/tc updateBuildCurrentPort -b ${branch} -n ${pkgname}
+${pb}/scripts/tc updateBuildStatus -b ${branch} -s PORTBUILD
+${pb}/scripts/tc updateBuildCurrentPort -b ${branch} -n ${pkgname} -d ${portdir}
 
 chroot=${pb}/${branch}
 packages=${pb}/packages/${branch}
@@ -282,10 +306,10 @@ elif [ "${major_version}" = "5" ]; then
         fi
         cp -p /lib/libc.so.6 ${chroot}/lib
     elif [ -f /lib/libc.so.7 ]; then
-	if [ -f ${chroot}/lib/libc.so.7 ]; then
-	    chflags noschg ${chroot}/lib/libc.so.7
-	fi
-	cp -p /lib/libc.so.7 ${chroot}/lib
+       if [ -f ${chroot}/lib/libc.so.7 ]; then
+           chflags noschg ${chroot}/lib/libc.so.7
+       fi
+       cp -p /lib/libc.so.7 ${chroot}/lib
     fi
 fi
 cp -p /rescue/ps ${chroot}/bin
@@ -412,17 +436,17 @@ else
   	>/dev/null 2>&1
 fi
 
-mkdir ${chroot}${X11BASE}
+mkdir -p ${chroot}${X11BASE}
 if [ $X_WINDOW_SYSTEM = "xfree86-3" ]; then
     mtree -deU -f ${chroot}/usr/src/etc/mtree/BSD.x11.dist -p ${chroot}${X11BASE} >/dev/null 2>&1
 else
-    if [ -f ${chroot}/a/ports/Templates/BSD.local.dist ]; then
-	mtree -deU -f ${chroot}/a/ports/Templates/BSD.local.dist -p ${chroot}${X11BASE} \
-		>/dev/null 2>&1
-    else
+#    if [ -f ${chroot}/a/ports/Templates/BSD.local.dist ]; then
+#	mtree -deU -f ${chroot}/a/ports/Templates/BSD.local.dist -p ${chroot}${X11BASE} \
+#		>/dev/null 2>&1
+#    else
 	mtree -deU -f ${chroot}/usr/src/etc/mtree/BSD.x11-4.dist -p ${chroot}${X11BASE} \
 		>/dev/null 2>&1
-    fi
+#    fi
 fi
 
 if [ ${ARCH} = "i386" -o ${ARCH} = "amd64" ]; then
@@ -529,6 +553,7 @@ if [ "${error}" = 0 ]; then
 	${pb}/scripts/tc updatePortLastStatus -d ${portdir} -b ${branch} -s ${status}
 	${pb}/scripts/tc updatePortLastBuiltVersion -d ${portdir} -b ${branch} -v ${pkgname}
 	${pb}/scripts/tc updatePortLastFailReason -d ${portdir} -b ${branch} -r "__nofail__"
+	execute_hook ${pb} "postPortBuild" "PACKAGE_NAME=${pkgname} BUILD=${branch} JAIL=${jail} PORTSTREE=${portstree} CHROOT=${chroot} STATUS=${status} PORTDIR=${portdir} PB=${pb}"
     else
 	cp ${chroot}/tmp/${pkgname}.log ${pb}/errors/${branch}/${pkgname}.log
 	if [ ${nolog} = 0 ]; then
@@ -538,7 +563,9 @@ if [ "${error}" = 0 ]; then
 	${pb}/scripts/tc updatePortLastBuilt -d ${portdir} -b ${branch}
 	${pb}/scripts/tc updatePortLastStatus -d ${portdir} -b ${branch} -s FAIL
 	${pb}/scripts/tc updatePortLastBuiltVersion -d ${portdir} -b ${branch} -v ${pkgname}
+	mark_failed ${pb} ${branch} ${pkgname} ${portdir}
         ${pb}/scripts/tc sendBuildErrorMail -d ${portdir} -b ${branch} -p ${pkgname}
+	execute_hook ${pb} "postPortBuild" "PACKAGE_NAME=${pkgname} BUILD=${branch} JAIL=${jail} PORTSTREE=${portstree} CHROOT=${chroot} STATUS=FAIL PORTDIR=${portdir} PB=${pb}"
     fi
 else
     cp ${chroot}/tmp/${pkgname}.log ${pb}/errors/${branch}/${pkgname}.log
@@ -551,7 +578,9 @@ else
     ${pb}/scripts/tc updatePortLastBuilt -d ${portdir} -b ${branch}
     ${pb}/scripts/tc updatePortLastStatus -d ${portdir} -b ${branch} -s FAIL
     ${pb}/scripts/tc updatePortLastBuiltVersion -d ${portdir} -b ${branch} -v ${pkgname}
+    mark_failed ${pb} ${branch} ${pkgname} ${portdir}
     ${pb}/scripts/tc sendBuildErrorMail -d ${portdir} -b ${branch} -p ${pkgname}
+	execute_hook ${pb} "postPortBuild" "PACKAGE_NAME=${pkgname} BUILD=${branch} JAIL=${jail} PORTSTREE=${portstree} CHROOT=${chroot} STATUS=FAIL PORTDIR=${portdir} PB=${pb}"
 fi
 
 cleanup ${chroot} ${noclean} ${error} "${cleandirs}" ${pkgname} ${pb} ${branch}
